# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = neoforge

# Mod properties
mod_version = 1.0.0-mc1.21
maven_group = cn.ksmcbrigade.mr
archives_name = MixinRuntime

# Minecraft properties
minecraft_version = 1.21

# Dependencies
neoforge_version = 21.0.167
